OnlineTicariOtomasyon/Models/Class/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineTicariOtomasyon.Models.Class
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(40)]
        public string CategoryName { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool Status { get; set; }
        public ICollection<Product> Products { get; set; }
    }
}

OnlineTicariOtomasyon/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;
using OnlineTicariOtomasyon.Models.Class;
using PagedList;
using PagedList.Mvc;


namespace OnlineTicariOtomasyon.Controllers
{
    public class CategoryController : Controller
    {
        OnlineTicariOtomasyon.Models.Class.Context context = new Models.Class.Context();
        // GET: Category
        public ActionResult Index(int page=1)
        {
            var results = context.Categories.Where(c => c.Status == true).ToList().ToPagedList(page,10);
            return View(results);
        }
        [HttpGet]
        public ActionResult CategoryAdd()
        {

            return View();
        }
        [HttpPost]
        public ActionResult CategoryAdd(Category category)
        {
            category.CreatedDate = DateTime.Now;
            category.Status = true;
            context.Categories.Add(category);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult CategoryDelete(int id)
        {
            var result = context.Categories.Find(id);
            result.Status = false;

            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult GetCategory(int id)
        {
            var result = context.Categories.Find(id);
            return View("GetCategory", result);

        }

        public ActionResult CategoryEdit(Category category)

        {
            var result = context.Categories.Find(category.Id);
            result.CategoryName = category.CategoryName;
            result.Description = category.Description;
            result.UpdatedDate = DateTime.Now;
            context.SaveChanges();
            return RedirectToAction("Index");


        }
    }


}

OnlineTicariOtomasyon/Views/Category/CategoryAdd.cshtml
@model OnlineTicariOtomasyon.Models.Class.Category
@{
    ViewBag.Title = "CategoryAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h5 class="alert alert-default-info"style="text-align:center" > Yeni Kategori Ekle</h5>

<form class="form-group" method="post">
    @Html.Label("Kategori Adı:")
    @Html.TextBoxFor(c => c.CategoryName, new { @class = "form-control" })

    @Html.Label("Kategori Açıklaması:")
    @Html.TextAreaFor(c => c.Description, new{@class = "form-control" })
    <br />
    
    <button class="btn btn-success">Kaydet</button>
    


</form>

OnlineTicariOtomasyon/Views/Category/GetCategory.cshtml
@model OnlineTicariOtomasyon.Models.Class.Category
@{
    ViewBag.Title = "GetCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h5 class="alert alert-default-info" style="text-align:center"><b style="color:red"  >@Model.CategoryName</b> Kategorisinde Güncelleme İşlemi Yapılacak</h5>

@using (Html.BeginForm("CategoryEdit", "Category", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori Adı:")
    
    @Html.TextBoxFor(x => x.CategoryName,new {@class="form-control" })

    @Html.Label("Kategori Açıklaması:")
    @Html.TextBoxFor(x => x.Description,new {@class="form-control" })
    @Html.HiddenFor(x => x.Id)
   



</div>

<button class="btn btn-info">Güncelle</button>
}

OnlineTicariOtomasyon/Views/Category/Index.cshtml
@using OnlineTicariOtomasyon.Models.Class
@using PagedList;
@using PagedList.Mvc;
@model  PagedList.IPagedList<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            
            <th scope="col">Kategori Adı</th>
            <th scope="col">Açıklama</th>
            <th scope="col">Oluşturma Tarihi</th>
            <th scope="col">Son Güncelleme Tarihi</th>
            <th scope="col">Durumu</th>
            <th scope="col">Sil</th>
            <th scope="col">Güncelle</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>

                <th>@item.CategoryName</th>
                <th>@item.Description</th>
                <th>@item.CreatedDate</th>
                <th>@item.UpdatedDate</th>
                <th>@item.Status</th>
                <th><a href="/Category/CategoryDelete/@item.Id" class="btn btn-danger">Sil</a></th>
                <th><a href="/Category/GetCategory/@item.Id" class="btn btn-info">Güncelle</a></th>


            </tr>
        }
    </tbody>

</table>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new { page }))
<a href="/Category/CategoryAdd" class="btn btn-primary">Kategori Ekle</a>