OnlineTicariOtomasyon/Controllers/CurrentPanelController.cs
using OnlineTicariOtomasyon.Models.Class;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineTicariOtomasyon.Controllers
{
    public class CurrentPanelController : Controller
    {
        Context context = new Context();
        // GET: CurrentPanel
        [Authorize]

        public ActionResult Index()
        {
            var currentMail = (string)Session["Email"];

            var result = context.Currents.FirstOrDefault(x => x.Email == currentMail);
            ViewBag.current = currentMail;


            return View(result);
        }
        public ActionResult Orders ()
        {
            var currentMail = (string)Session["Email"];
            var id = context.Currents.Where(x => x.Email == currentMail.ToString()).Select(y => y.Id).FirstOrDefault();
            var result = context.SalesMoves.Where(c => c.Current.Id == id).ToList();
            return View(result);
        }
    }
}

OnlineTicariOtomasyon/Views/CurrentPanel/Index.cshtml
@model OnlineTicariOtomasyon.Models.Class.Current
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CurrentPanelLayout.cshtml";
}

<h5 class="alert alert-default-info" style="text-align:center"><b style="color:red">Bilgilerim</b></h5>

@using (Html.BeginForm("Index", "CurrentPanel", FormMethod.Post))

{
    <table class="table table-bordered">
        <tbody>
            
            <tr>
                <td>
                    <label>Mail Adresi:@HttpContext.Current.User.Identity.Name</label>
                </td>

            </tr>
            <tr>
                <th>@Html.Label("Ad")</th>
                <td>@Html.TextBoxFor(c => c.CurrentName, new { @class = "form-control" })</td>
            </tr>
            <tr>
                <th>@Html.Label("Soyad")</th>
                <td>@Html.TextBoxFor(c => c.CurrentSurname, new { @class = "form-control" })</td>
            </tr>
            <tr>
                <th>
                    @Html.Label("Şehir")
                </th>
                <th>@Html.TextBoxFor(c => c.City, new { @class = "form-control" })</th>
            </tr>
            <tr>
                <th>
                    @Html.Label("Şifre")
                </th>
                <td>@Html.TextBoxFor(c => c.CurrentPassword, new { @class = "form-control" })</td>
            </tr>
        </tbody>

    </table>
    <button class="btn btn-warning">Bilgilerimi Güncelle</button>
}

OnlineTicariOtomasyon/Views/CurrentPanel/Orders.cshtml
@using OnlineTicariOtomasyon.Models.Class
@model List<SalesMove>
@{
    ViewBag.Title = "Orders";
    Layout = "~/Views/Shared/_CurrentPanelLayout.cshtml";
}

<h3 class="alert alert-default-info" style="text-align:center"><b style="color:red">Sipariş Geçmişi</b></h3>


<table id="tableSaleDetail" class="table table-bordered">

    <tbody>
        <tr>
            <th>Ürün Adı</th>
            <th>Sipariş Tarihi</th>
            <th>Adet</th>
            <th>Fiyat</th>

        </tr>
        <tr>
            @foreach (var item in Model)
            {
            <tr>

                <td>@item.Product.ProductName</td>
                <td>@item.Date_</td>
                <td>@item.Amount</td>
                <td>@item.TotalPrice</td>
            </tr>

        }

            </tr>
        </tbody>
    </table>


    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>




    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

    <script>
        $('#tableSaleDetail').dataTable({});
    </script>