OnlineTicariOtomasyon/Models/Class/Current.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineTicariOtomasyon.Models.Class
{
    public class Current
    {
        [Key]
        public int Id { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string CurrentName { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string CurrentSurname { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string CurrentDescription { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(40)]
        public string City { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(40)]
        public string Email { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(40)]
        public string CurrentPassword { get; set; }
        public bool Status { get; set; }

        public ICollection<SalesMove> SalesMoves { get; set; }

    }
}

OnlineTicariOtomasyon/Controllers/CurrentController.cs
using OnlineTicariOtomasyon.Models.Class;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineTicariOtomasyon.Controllers
{
    public class CurrentController : Controller
    {
        // GET: Current
        Context context = new Context();
        public ActionResult Index()
        {
            var result = context.Currents.Where(x => x.Status == true).ToList();
            return View(result);
        }
        [HttpGet]
        public ActionResult CurrentAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CurrentAdd(Current current)
        {
            var result = context.Currents.Add(current);
            result.Status = true;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CurrentDelete(int id)

        {
            var result = context.Currents.Find(id);
            result.Status = false;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GetCurrent(int id)
        {
            var current = context.Currents.Find(id);
            return View("GetCurrent", current);


        }
        public ActionResult CurrentEdit(Current current)
        {
            var result = context.Currents.Find(current.Id);
            result.CurrentName = current.CurrentName;
            result.CurrentSurname = current.CurrentSurname;
            result.CurrentDescription = current.CurrentDescription;
            result.Email = current.Email;
            result.Status = current.Status;
            result.City = current.City;
            context.SaveChanges();
            return RedirectToAction("Index");


        }
        public ActionResult CurrentSalesHistory(int id)
        {
            var results = context.SalesMoves.Where(x => x.CurrentId == id).ToList();
            var currentName = context.Currents.Where(x => x.Id == id).Select(y => y.CurrentName + " " + y.CurrentSurname).FirstOrDefault();
            ViewBag.current = currentName;
            return View(results);

        }
    }
}

OnlineTicariOtomasyon/Views/Current/CurrentAdd.cshtml
@model OnlineTicariOtomasyon.Models.Class.Current
@{
    ViewBag.Title = "CurrentAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h5 class="alert alert-default-info" style="text-align:center"> Yeni Kategori Ekle</h5>

<form class="form-group" method="post">
    @Html.Label("Cari Adı:")
    @Html.TextBoxFor(c => c.CurrentName, new { @class = "form-control" })

    @Html.Label("Cari Soyadı:")
    @Html.TextBoxFor(c => c.CurrentSurname, new { @class = "form-control" })

    @Html.Label("Açıklama:")
    @Html.TextBoxFor(c => c.CurrentDescription, new { @class = "form-control" })

    @Html.Label("Şehir:")
    @Html.TextBoxFor(c => c.City, new { @class = "form-control" })

    @Html.Label("Email Adresi:")
    @Html.TextBoxFor(c => c.Email, new { @class = "form-control" })
    <br />

    <button class="btn btn-success">Kaydet</button>



</form>

OnlineTicariOtomasyon/Views/Current/CurrentSalesHistory.cshtml
@using OnlineTicariOtomasyon.Models.Class
@model List<SalesMove>
@{
    ViewBag.Title = "CurrentSalesHistory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h5 class="alert alert-default-info" style="text-align:center"><b style="color:red">@ViewBag.current</b> Adlı Cariye Ait Satış Geçmişi </h5>
<div>
    <section class="content">
        <div class="container-fluid">
            <table class="table table-borderes">
                <tr>
                    <th>#</th>
                    <th>Ürün Adı</th>
                    <th>Satış Yapan Personel</th>
                    <th>Fiyat</th>
                    <th>Adet</th>
                    <th>Toplam Tutar</th>
                    <th>Satış Tarihi</th>
                    <th>Operasyon</th>
                </tr>
                @foreach (var item in Model)
                {
                                      
                        <tr>

                            <td>@item.Id</td>
                            <td>@item.Product.ProductName </td>

                            <td>@item.Employee.EmployeeName @item.Employee.EmployeeSurname</td>

                            <td>@item.Price</td>
                            <td>@item.Amount</td>
                            <td>@item.TotalPrice</td>
                            <td>@item.Date_</td>
                            <td><a href="#" class="btn btn-default" style="background-color:lightyellow">Yazdır</a></td>
                        </tr>


                }


            </table>
        </div>
    </section>



</div>

OnlineTicariOtomasyon/Views/Current/GetCurrent.cshtml
@model OnlineTicariOtomasyon.Models.Class.Current 
@{
    ViewBag.Title = "GetCurrent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h5 class="alert alert-default-info" style="text-align:center"><b style="color:red">@Model.CurrentName @Model.CurrentSurname</b> Carisinde Güncelleme İşlemi Yapılacak</h5>

@using (Html.BeginForm("CurrentEdit", "Current", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Cari Adı:")

    @Html.TextBoxFor(c => c.CurrentName, new { @class = "form-control" })

    @Html.Label("Cari Soyadı:")
    @Html.TextBoxFor(d => d.CurrentSurname, new { @class = "form-control" })

    @Html.Label("Açıklama:")
    @Html.TextBoxFor(d => d.CurrentDescription, new { @class = "form-control" })

    @Html.Label("Şehir:")
    @Html.TextBoxFor(d => d.City, new { @class = "form-control" })

    @Html.Label("Mail Adresi:")
    @Html.TextBoxFor(d => d.Email, new { @class = "form-control" })

    @Html.Label("Durumu:")
    @Html.TextBoxFor(d => d.Status, new { @class = "form-control" })


    @Html.HiddenFor(d => d.Id)

</div>

    <button class="btn btn-info">Güncelle</button>
}

OnlineTicariOtomasyon/Views/Current/Index.cshtml
@using OnlineTicariOtomasyon.Models.Class
@model List<Current>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<p>Toplamda @Model.Count() adet  cari kaydı vardır.</p>
<table id="currentIndex" class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Cari Adı</th>
            <th scope="col">Cari Soyadı</th>
            <th scope="col">Açıklama</th>
            <th scope="col">Şehir</th>
            <th scope="col">Email Adresi</th>
            <th scope="col">Durum(Aktif/Pasif)</th>
            <th scope="col">Sil</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Operasyon</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>


                <th>@item.Id</th>
                <th>@item.CurrentName</th>
                <th>@item.CurrentSurname</th>
                <th>@item.CurrentDescription</th>
                <th>@item.City</th>
                <th>@item.Email</th>
                <th>@item.Status</th>
                <th><a href="/Current/CurrentDelete/@item.Id" class="btn btn-danger">Sil</a></th>
                <th><a href="/Current/GetCurrent/@item.Id" class="btn btn-info">Güncelle</a></th>
                <th><a href="/Current/CurrentSalesHistory/@item.Id" class="btn btn-success">Satış Geçmişi</a></th>


            </tr>
        }
    </tbody>

</table>
<a href="/Current/CurrentAdd/" class="btn btn-primary">Yeni Cari Ekle</a>

<link href="~/Content/bootstrap.css" rel="stylesheet" />

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>




<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#currentIndex').dataTable({});
</script>